### ISSUE TITLE
"Pill fading" doesn't work after swipe gesture

### ISSUE THREAD

**Issue by DelcanProbably** [zacharee/nobar-issues#100]
**Describe the bug**
When using the Pill Fading feature to hide the pill after a set delay, the pill usually does not hide after performing swipe gestures, however generally works after taps and swipe and hold gestures.

**To Reproduce**
1. Enable *Fade Pill After Specified Delay* under *Behaviour* > *Pill Fading*
2. Make sure some horizontal swipe gestures are enabled.
3. Try using these swipe gestures and sooner or later the pill will not fade. 

**Expected behavior**
The pill should fade consistently when using swipe gestures.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - Android Version: 9
 - Navigation Gestures version: 1.11.7

**Comment by zacharee** [comment]
Does this still occur on 1.11.12 or 1.12.1?
