### ISSUE TITLE
Pill in landscape mode and keyboard. 

### ISSUE THREAD

**Issue by llreizh** [zacharee/nobar-issues#101]
First, Pill interfere with keyboard, make it difficult to tap space button. Please add option to pill intentionaly above/bellow keyboard (not overlap).

Second, in landscape mode, 
especially in game, pill placed in bellow. Making it cumbersome. Please make it so pill can be placed in side (no change from when potrait mode)

Thank you
![IMG-20190513-WA0001](https://user-images.githubusercontent.com/50562226/57592292-26d03400-7560-11e9-96d9-33537c47f5bd.jpg)
![IMG-20190513-WA0002](https://user-images.githubusercontent.com/50562226/57592301-30f23280-7560-11e9-942b-15146557b4c3.jpg)

**Comment by zacharee** [comment]
These are both already existing options.

Settings>>Behavior>>General>>Don't Move Pill when Keyboard Shown

Settings>>Experimental Settings>>Anchor Pill
