### ISSUE TITLE
Empty black bar and some app's component got warped under the screen

### ISSUE THREAD

**Issue by howardlie** [zacharee/nobar-issues#103]
**Describe the bug**
A black bar is shown in some apps (SAS 4 for eg.) and some app's component got warped under the screen.

**To Reproduce**
1. I use splitted pill
2. Native navbar hidden
3. Black bar occurs on SAS 4, ATV Cloud and I believe many other app including my native camera app
4. App's component such as notification bubble got warped under the screen

**Expected behavior**
Empty black bar is supposed to be native navigation background, it shouldn't be there when Native navbar is disabled/hidden.

App's component should fit inside the screen normally like when I enable native navbar.  This problem didn't exist in the previous version.

**Screenshots/Recordings**
https://imgur.com/a/Hx7aOId

**Smartphone :**
 - Device: Zenfone Max Pro M1 (3/32GB)
 - Android Version: Oreo 8.1.0
 - Navigation Gestures version: 1.11.7

**Comment by zacharee** [comment]
This can't be fixed.
