### ISSUE TITLE
Move the pill to the bottom of the screen

### ISSUE THREAD

**Issue by tjveith** [zacharee/nobar-issues#108]
**What is the current behavior that should be changed?**

Nova Launcher, the pill appears over top of the dock.

**How should this behavior be changed?**

The pill needs to appear underneath the dock in Nova Launcher.

**Additional context**
![Screenshot_2019-05-16-09-03-19](https://user-images.githubusercontent.com/47465915/57869399-d0f6c880-77b9-11e9-9643-23ac8a4029f8.png)

**Comment by zacharee** [comment]
Sorry, but we can't give the pill a dedicated space.

You can go to Settings>>Behavior>>Blacklisting>>Hide Pill in Selected Apps and choose Nova Launcher to make the pill completely disappear. Or, you could set the pill's vertical position to 0.
