### ISSUE TITLE
Anchor not working in reverse landscape

### ISSUE THREAD

**Issue by llreizh** [zacharee/nobar-issues#117]
**Describe the bug**
Anchor pill working as intended when in landscape mode( device up in left), but when fliped/reversed landscape (device up in right), pill stop working. Flip again and pill shown.

**To Reproduce**
1. Activate anchor pill option
2. Spin orientation in lanscape. So far everything ok.
3. Flip to reverse lanscape mode. Pill gone

Max pro m1
ng vers 1.13.10

**Comment by lulajardim** [comment]
This also happens to me but not all apps.
It happens on Youtube while playing video on full screen and on most landscape games.
It also happens on Netflix but only while status bar is hidden. If i touch the screen first, the status bar will be shown and gestures will work normally.

I'm pretty sure this is related to Android's Immersive Mode

The orientation is landscape mode with the bottom of the device facing left

Device is Galaxy Note 9 running Android 9
ng version 1.13.10
