### ISSUE TITLE
1.15.8 Google Play Version Crushed

### ISSUE THREAD

**Issue by chenqu1989** [zacharee/nobar-issues#121]
Dear Devs:

**Describe the bug**
Updated to 1.15.8 Version from Google Play,thens Nobar always crushed even after several reboots.
Becauser I can't user back button function.Finally I uninstall it and use 1.15.7 Version from github,it works normally.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XZP
 - Android Version: Android 9--2019/6/1 patched
 - Navigation Gestures version: 1.15.8

**Additional context**

**Comment by zacharee** [comment]
Fixed in 1.15.9
