### ISSUE TITLE
previous app(Nougat+) doesn't work Ver 1.17.2

### ISSUE THREAD

**Issue by zprood** [zacharee/nobar-issues#122]
**Describe the bug**
Xiaomi Mix3 with Android 9 (MIUI 10), when swipe to trigger Preivous App, it just works randomly. 

**To Reproduce**
1. open App A, back to home screen.
2, open App B, swipe left and hold.
3, switch to App A successfully.
4. swipe left and hold again, blink on App A and stayed, doesn't switch to App B. 

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Mix3]
 - Android Version: [Android Pie]
 - Navigation Gestures version: [1.17.2]

**Comment by zacharee** [comment]
The next beta version will have a compatibility option to set the delay of the simulated double-tap for this gesture.
