### ISSUE TITLE
The app lags after the last update the gestures are responding after a couple of seconds!! (Sometimes)

### ISSUE THREAD

**Issue by abhishek429998** [zacharee/nobar-issues#123]
**less responsive after last update**
The last update made the app gestures relatively slow and also has started rejecting gestures often when I wanted it to work several times

**Device: Mi A2**
 - Android Version: [pie 9 security patch September 5]
 - Navigation Gestures version: [1.18.4]

**Comment by zacharee** [comment]
Turn on Full Overscan under Experimental Settings.
