### ISSUE TITLE
Security problem while try to activate the ADB command

### ISSUE THREAD

**Issue by ghost** [zacharee/nobar-issues#135]
I tried to type in the ADB command but after I hit enter it said something about a security error. I want to use this app the there's a problem. Please someone help.

- Redmi 5 Plus with MIUI 10.2
- Only "Security" app used for security
- Using the standard Micro USB cable
- Enabled USB debugging
- Locked bootloader

PC

- Have Malwarebytes antivirus (Free version)
- Windows 10
- Used the second usb port
- Downloaded adb
- Tried with cmd and PowerShell as well

**Comment by zacharee** [comment]
Go to Developer Options and enable `USB debugging (Security settings)`.

**Comment by ghost** [comment]
I enabled it first time. It say this: 

Operation not allowed: java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
