### ISSUE TITLE
Galaxy S9 - Navigation Gestures Failure

### ISSUE THREAD

**Issue by allenmarkham3** [zacharee/nobar-issues#16]
**Describe the bug**
Navigation Gestures - Gestures randomly stop working.

**To Reproduce**
I have found no way to reproduce other than the passage of time.  It seems to be random with no common action that I can see that precipitates gesture failure. I'm using basic gestures- 'Swipe Left'-Back, 'Swipe Right'-Previous App, 'Swipe Up'-Home, 'Swipe Up and Hold'-Recent Apps.

Using the 'Enable Gesture Pill' and 'Hide Navigation Bar' sliders to turn off then back on restores the Vibration Behavior, but not Gestures.

Phone must be restarted to get Gestures back.  (There is a suggestion that toggling Accessibility Off then back ON restores Gestures - I'll try that on next failure).

**Expected behavior**
Gestures to work.

**Screenshots/Recordings**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - Android Version: Oreo 8.0.0 Samsung Experience Version: 9.0
 - Navigation Gestures version: 1.6.1-18_12_24_2149_59 (updated 12/25)

**Additional context**
Crashlytics ID:  1545726853629 (updated 12/25)

**Comment by allenmarkham3** [comment]
I can confirm that toggling 'Accessibility' Off then On again restores the navigation gestures.  I does seem, however, that the battery (at least wireless charging) is affected by the reported "problem" and is not solved by the 'Accessibility' solution - a battery charging effect is speculation at this point as the charging problem may only be a coincidence.

**Comment by allenmarkham3** [comment]
Comments updated to reflect the 12/24 version update and to indicate that the problem reported is still present.

**Comment by zacharee** [comment]
Do you have any of Samsung's battery optimization features activated, like App Power Monitor?

**Comment by allenmarkham3** [comment]
No – Navigation Gestures is among those marked as ‘Unmonitored apps’

________________________________

**Comment by zacharee** [comment]
Deactivate it completely.

**Comment by allenmarkham3** [comment]
Done – ‘App power monitor’ is off.

________________________________

**Comment by allenmarkham3** [comment]
Navigation Gestures worked all morning but after returning from being out this  afternoon gestures have once again stopped working.  The ‘Pill’ shows – but was not immediately visible after logging in until I touched the screen – the vibration, animation and audio behaviors continued working – all that was missing was the actual gestures.  Toggling the  “Accessibility”  services for Navigation Gestures OFF then back ON restored the gestures.

Any ideas?

Allen Markham

(while at home I use Wi-Fi and have no Bluetooth devices connected, when out of the house Wi-Fi is not always available and the phone is connected via Bluetooth to the car – if any of that might make a difference).



________________________________

**Comment by zacharee** [comment]
Do you have any other battery "management" apps, like Greenify, active?

Have you tried deactivating the stock Android battery optimizations for Navigation Gestures?

**Comment by allenmarkham3** [comment]
No other battery "management" apps.
I used the battery section in 'Device Maintenance' and deactivated "App Power Monitor".   (If the power monitor was on Navigation Gestures would be among the unmonitored apps).  "Power Saving Mode" is OFF.  Is there somewhere else I should be looking for other battery optimizations?

Within "Apps" settings 'Navigation Gestures Premium' battery optimization may have been optimized.  It is now OFF.

**Comment by allenmarkham3** [comment]
After charging over night the pill no longer visible on the home screen.

I've now turned Navigation Gestures off but have left it installed.  I will continue to monitor this site and check for 'Beta' updates.

**Comment by zacharee** [comment]
Is 1.7.0 any better?

**Comment by allenmarkham3** [comment]
Just now installed it – from the apk not Google Play.  I’ll let you know how it goes.  FYI: The last several releases have worked for ½ a day or so and seem to be better from the apk file than through Google Play – because of a difference in how they install?

Thanks for the follow up – much appreciated

Allen Markham

________________________________

**Comment by zacharee** [comment]
The install source shouldn't matter.

**Comment by allenmarkham3** [comment]
Good to know, thanks
________________________________

**Comment by allenmarkham3** [comment]
After most of yesterday and this morning,  it seems to be my big is resolved.

Thanks for your help

Allen Markham
________________________________

**Comment by allenmarkham3** [comment]
That's 'my bug' that is resolved.
________________________________

**Comment by zacharee** [comment]
I'm closing this for now. Reopen it if the issue comes back.
