### ISSUE TITLE
The under part on Lockscreen ist hidden

### ISSUE THREAD

**Issue by groegerjo** [zacharee/nobar-issues#17]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.

**Smartphone (please complete the following information):**
 - Android Version: [e.g. Oreo, e.g. 7.1.2, e.g. 28]
 - Navigation Gestures version: [e.g. 1.4.0-18_12_02_1010_57]

**Additional context**
Version: 1.5.0-18_12_16_1104_51 Since that version I have the problem, that the lock icon and shortcuts are hidden on Lockscreen. This error is on my Nvidia Shield Tablet K1 (LOS14.1) and on my stock Huawei Mate 10 Pro. But at all it's a fantastic app to get smooth gestures.

**Comment by zacharee** [comment]
Go to Settings>>Behavior and activate "Don't Hide NavBar on Lock Screen."
