### ISSUE TITLE
Rework vertical swipe distance

### ISSUE THREAD

**Issue by shmykelsa** [zacharee/nobar-issues#20]
**Why do I think this is necessary**

When using Navigation Gestures with pill mode (so no split pill) most of the people would place the pill on the bottom of the screen. For the sake of explaining, let's assume I've set a pill to be 89 px above the edge of the screen. 

Then I set both the swipe down & swipe down and hold gesture. 

Now I want my vertical swipe distance up a bit, so I set it somewhere like 100px, so that the pill won't actually misunderstand some horizontal swipes because I've shifted my finger a little bit up or down.

The problem is that now both swipe down and swipe down and hold gestures are unable to use, because the vertical swipe distance is set so high that the swipe down gestures simply won't have enough space below to register them as a gesture at all.

**Possible solutions:**

1. Split the Y distance settings in two, an upper one and a lower one
2. Set the swipe down gestures to ignore the Y distance if above the distance of the pill from the edge
3. Have an arbitrary Y- swipe distance proportional to the distance of the pill from the edge

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases/tag/1.7.1-19_01_01_1824_16
