### ISSUE TITLE
Pill shifts up whenever an app goes fullscreen

### ISSUE THREAD

**Issue by shmykelsa** [zacharee/nobar-issues#21]
**How to reproduce this behaviour**
It happens whenever an app goes fullscreen

**What is the current behavior that should be changed?**
The pill shifts up, more or less with a distance of its own height

**How should this behavior be changed?**
The pill should not move, because it gets in the way of buttons and concent

**Additional context**
Reproduced on a LG V10 running LG Android 7.0

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases/tag/1.7.1-19_01_01_1824_16
