### ISSUE TITLE
Pill gets hidden when keyboard is shown

### ISSUE THREAD

**Issue by shmykelsa** [zacharee/nobar-issues#22]
**Describe the bug**
Title says it all

**To Reproduce**
1. Simply open up the keyboard. The pill will totally disappear

**Expected behavior**
The pill should be above the keyboard

**Smartphone (please complete the following information):**
 - Device: LG V10
 - Android Version: 7.0
 - Navigation Gestures version: 1.7.1-19_01_01_1824_16

**Additional context**
Used to work as expected before

**Comment by zacharee** [comment]
Are you sure it's actually gone? The default pill color is the exact color of the LGUX keyboard.

**Comment by shmykelsa** [comment]
I don't even have LGUX Keyboard. I had to enable "Show navbar with keyboard" otherwise it would look like this 

![image](https://user-images.githubusercontent.com/9965637/50577850-abcc7380-0e31-11e9-9ae2-b7f367ec0a66.png)

**Comment by shmykelsa** [comment]
And I don't have the "Don't move pill when keyboard shown" activated

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases/tag/1.7.3-19_01_03_1732_47

**Comment by shmykelsa** [comment]
Bug is again present with 1.7.8-19_01_14_2231_41

**Comment by zacharee** [comment]
I can't reproduce.
