### ISSUE TITLE
App list when selecting gesture setting

### ISSUE THREAD

**Issue by Veed004** [zacharee/nobar-issues#23]
In setting page, when choosing launch shortcut or launch app on swiping up, app list does not get shown

**Comment by shmykelsa** [comment]
I can confirm this, though going to recent pages and going to Navigation Gestures again solves the issue for me.  And, actually, it's on every single gestures this issue, not only swiping up.

(1.7.1-19_01_01_1824_16)

**Comment by shahedimran** [comment]
Nice

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases/tag/1.7.3-19_01_03_1732_47
