### ISSUE TITLE
Pill vanishes constantly, Note 9

### ISSUE THREAD

**Issue by ctolmen** [zacharee/nobar-issues#27]
**Describe the bug**
It works for a few seconds after a reboot or after opening settings, then vanishes. It worked perfectly 2 versions ago. Never failed. After an update less than 2 months ago or so, it just never works. Makes me sad 😑 Battery management is off. 

**To Reproduce**
Can get it to work for a few seconds after disabling and then re-enable.

**Smartphone (please complete the following information):**
Note 9 SM-N960U Android 8.2.0 Kernel 4.9.65
1.7.4-19_01_03_2221_14

**Comment by zacharee** [comment]
Please follow the template for bug reports.

**Comment by zacharee** [comment]
Do you have App Power Monitor completely deactivated?

**Comment by ctolmen** [comment]
Yes I do. I uninstalled the bar and have just been using the samsung one handed gestures now since the bar hasn't worked since maybe Oct. I'll have to try again one day.
