### ISSUE TITLE
Add arrow navigation buttons 

### ISSUE THREAD

**Issue by steadfasterX** [zacharee/nobar-issues#29]
When navigating through text I really miss the left and right arrow from LOS. It's quite hard to find the right position in a text by just touching the screen . Would it be possible to add such functionality ? I am on OnePlus 9.0 if that matters.

**Comment by zacharee** [comment]
It would be root only.

**Comment by steadfasterX** [comment]
Yea I see but would be fully ok (at least for me)

**Comment by zacharee** [comment]
1.14 has root actions. You can set a gesture to send a custom keycode. Left would be 21 and right would be 22.
