### ISSUE TITLE
Issues when running android auto

### ISSUE THREAD

**Issue by gadinaveh** [zacharee/nobar-issues#30]
Hi

As this is my first post - thanks for a great app, I love the ability and the flexibility.

I run into issues when I use android auto. My car has android auto, and when i connect my phone (US Samsung unlocked S9+, official Samsung Android 8 ROM), I get a flickering navigation bar. My set up is to hide the nav bar in all cases. After using the phone in the car, in some cases I need to toggle the show/hide option for the nav bar to get the gestures to work correctly again.

The expected behavior would be to either switch to fully functioanl nav bar while in auto, or, fully functional gesture support

What I actually get is a difficult to use nav option while using android auto.

**Smartphone (please complete the following information):**
 - Device: Unlock Samsung S9+
 - Android Version: 8.0
 - Navigation Gestures version: 1-7-5-19_01_06_1936_11, with premium key

**Comment by zacharee** [comment]
Show Pill in Car Mode needs to be disabled on TouchWiz.

**Comment by gadinaveh** [comment]
I am using MS launcher, not touchwiz, would that make a difference?

**Comment by zacharee** [comment]
TouchWiz is the entire operating system.

Sent from Nine
________________________________

**Comment by gadinaveh** [comment]
This option (navigation gestures - settings - behavior - pill hiding) is already turned off and still happens.

All three options in pill hiding (hide after delay, hide in fullscreen apps, show pill in car mode) are turned off

**Comment by zacharee** [comment]
Does this still happen with 1.7.8 or 1.7.12?

**Comment by gadinaveh** [comment]
I just installed the latest - will check with my car today.

**Comment by gadinaveh** [comment]
I have not yet checked with my car, but saw a similar behavior today in a phone call - the phone screen came up, and the navbar started flickering. my config is still the same 

navigation gestures - settings - behavior - pill hiding is already turned off 
All three options in pill hiding (hide after delay, hide in fullscreen apps, show pill in car mode) are turned off

Still need to check with the car

**Comment by zacharee** [comment]
Do you have Navigation Immersive enabled in the app?

**Comment by gadinaveh** [comment]
Assuming this relates to Compatibility | enable immersive navigation mode - no, it is off. All the compatibility and experimental switches are off

FYI, Behavior | Pill Hiding | Show pill in car mode is turned off, however, the pill still shows up in car mode (android auto is on when connected to the car)

Is there a way for me to find the configuration and then attach here?

**Comment by gadinaveh** [comment]
I just installed 1.7.13 and now the flicker happens always, not only in Android auto. I have gestures enabled and turned on showing the navigation bar - then I get the flicker. If the navbar is hidden there is no issue. Hope that helps.

**Comment by zacharee** [comment]
I don't see the flickering on a Note 8 on Pie or an LG G6 on Oreo.

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases/tag/1.7.14

Found what I think you're talking about. Try 1.7.14.

**Comment by gadinaveh** [comment]
I just downloaded and tried 1.7.14. Turned on gestures as well as showing navabr - flickering still there.

Did another test. My default launcher is Microsoft launcher. As I also have Action Launcher installed, made that my default launcher - same issue, flickering is there. Made nova launcher the default launcher - no flickering significantly reduced. 

please note (and sorry for forgetting to mention) - my navbar is set to autohide in system settings (can this be "confusing" for gestures?).

**Comment by zacharee** [comment]
Can you record it happening?

Sent from Nine
________________________________

**Comment by gadinaveh** [comment]
How do I do that?

**Comment by gadinaveh** [comment]
Ok, another test - in the system settings, turned off the option to have the navbar auto-hide. flickering is now gone

**Comment by gadinaveh** [comment]
one more issue i found - when toggling gestures' option to show/hide the navbar, the system settings for applying current theme to the navbar is lost - mine was on, i made the navbar visible and then hid it and then made it visible again. after the last action the "apply theme" option setting was reset (to off). i was able to repro that

**Comment by gadinaveh** [comment]
One thought - it looks like when the system setting for the navbar is autohide, gestures is trying to show it, but the system tries to hide which could be creating the flicker effect.

**Comment by zacharee** [comment]
You can't have the system nav hider activated when you have this app's on as well.

Navigation Gestures is supposed to turn it off automatically on TouchWiz if you have WRITE_SECURE_SETTINGS granted, but it might be broken on Pie.

As for the color, Navigation Gestures forces it black on TouchWiz (again if WSS is granted), so that there's no white line at the bottom of the screen if you don't have Full Overscan enabled.

Sent from Nine
________________________________

**Comment by gadinaveh** [comment]
That makes sense, was not aware of that. as for the OS version, this 8.0 (US), not Pie. 

regarding the theme - I think the right behavior would be to restore all settings the way they were, including the theme

**Comment by zacharee** [comment]
Sorry, got confused.

The current behavior _is_ to restore the color state, but it can get messed up.

**Comment by gadinaveh** [comment]
Thanks for the update, will wait for the fix on that.

As a suggestion - if possible, will be useful to let the user know (on a Samsung device) that they need to turn off the autohide if it is on during installation, or, if they turn it on at a later time.

**Comment by zacharee** [comment]
I found a mistake in the code that forces TouchWiz' auto-hide feature off, which is now fixed.

**Comment by zacharee** [comment]
If the Android Auto issue fixed now that you turned the hider off?

**Comment by gadinaveh** [comment]
i have not had a chance to test with a car, will do this afternoon. when do you think you will have the next version so I can test with it?

**Comment by gadinaveh** [comment]
I installed the just released 1.7.15 - the color setting is still lost on hide and show of the navbar. Yet to test with a car, will do shortly

**Comment by gadinaveh** [comment]
It now works (1.7.15) correctly with Android Auto.

Few things I noticed

- When the navbar is displayed in carmode, the color/theme setting is respected (the gestures setting is hide navbar)
- I have the config to show navbar on lock screen. When I unlock the phone, there is a noticeale delay until the navbar is re-hidden
- At one point, the navbar did not go away after care mode was terminated (I got out of the car). I could not reproduce this

**Comment by zacharee** [comment]
It might be a different navigation bar that uses different settings for the colors, so it reads the right values.

That can't be avoided. It hides as quickly as possible.

I've seen this sometimes, but it's not reliable enough (and I'm not in the car enough) to debug. I think the device just gets overloaded because of all the UI changes, so some things are just never executed.

**Comment by gadinaveh** [comment]
Got it.

Thanks for the support - I like the app a lot, the experience is great. Will let know if I run into other issues.
