### ISSUE TITLE
Unhide is very slow with 1.7.8-19_01_14_2231_41

### ISSUE THREAD

**Issue by shmykelsa** [zacharee/nobar-issues#35]
When pill gets hidden, it's a matter of 2 to 3 seconds to have the pill back up

**Comment by zacharee** [comment]
Follow a template please.

**Comment by shmykelsa** [comment]
**Describe the bug**
Whenever the pill gets hidden, whether automatically or by gesture, to get it back up again it's very slow 2-3 seconds

**To Reproduce**
1. Pill is hidden
2. Tap/swipe up on the pill to get unhide it

**Expected behavior**
The pill should be back up again quickly

**Smartphone (please complete the following information):**
-LG V10
-Android 7.0
-See title for version

**Comment by zacharee** [comment]
I'm unable to reproduce this issue, even on a really slow emulator.

**Comment by shmykelsa** [comment]
Seems like wiping datas of the app solved both this and #22 , therefore, I'm considering this solved.
