### ISSUE TITLE
Pill "sticks" to right side in portrait view

### ISSUE THREAD

**Issue by sansnil** [zacharee/nobar-issues#38]
**Describe the bug**
The pill keeps reverting to the far right side of the screen while in portrait mode. It can be moved back to the center but eventually reappears 'stuck' to the right side after turn the device (Note 8) back on.

**To Reproduce**
1. Install app.
2. Turn screen on.
3. Observe pill in the far right position without having been moved there.

**Expected behavior**
The pill would default to the center position unless being moved or held.

**Screenshots/Recordings**
LMK if helpful to provide.

**Smartphone (please complete the following information):**
 - Device: Samsung Note8
 - Android Version: Oreo 8.0
 - Navigation Gestures version: 1.7.10-19_01_16_0840_56

**Additional context**
n/a

**Comment by runtimeErr0r** [comment]
I can confirm the same behaviour on my S8, also with Oreo 8.0 Stock and same APP version. When I press the pill, it goes correctly to the center again

![screenshot_20190116-192503_telegram](https://user-images.githubusercontent.com/5368017/51316241-5c528e00-1a54-11e9-9bb6-8f88c3d600e2.jpg)

**Comment by zacharee** [comment]
Does this help: https://github.com/zacharee/nobar-issues/releases/tag/1.7.11

**Comment by sansnil** [comment]
That one keeps crashing every time I try to open it.

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases/tag/1.7.12

**Comment by runtimeErr0r** [comment]
> https://github.com/zacharee/nobar-issues/releases/tag/1.7.12

For me it fixed it, the only apreciable thing is that the pill flickers during some milliseconds after I unlock the device, being seen for some naneseconds at the right before going to the center again, but nothing important nor annoying. Thanks!

**Comment by sansnil** [comment]
Now fixed for me as well - thanks!
