### ISSUE TITLE
Flashlight toggle not working properly

### ISSUE THREAD

**Issue by willx777** [zacharee/nobar-issues#39]
As soon as Navigation Gesture is enabled, the Flashlight toggle in Quick setting is not working properly.

When I click the toggle, the flashlight is on for a second, then turns itself off immediately. 

If I disable Navigation Gesture, the Flashlight toggle is back to normal. 

FYI, I'm running the latest Beta version 1.7.12 on Note9 Pie.

**Comment by zacharee** [comment]
Try this version: https://github.com/zacharee/nobar-issues/releases/tag/1.7.13

Enable the Flashlight Fix option in Settings>>Compatibility.

**Comment by willx777** [comment]
Thanks. I've downloaded and installed that version and enabled it in Comptibility but it didn't fix. 

FYI, I don't assign Flashlight action to any gesture.

Also, on the Lock screen, the left and right bottom 2 shortcuts are moved down and hidden more than 80% of the icon.

Lastly, in the Camera app, there is a big black gap at the bottom. All other apps I tested don't have this issue.

Thanks

**Comment by zacharee** [comment]
If you didn't assign a gesture to the flashlight action, then the flashlight controller doesn't activate at all, and there's nothing from this app that should interfere with other toggles. Are you sure it's this app?

Go to Settings>>Behavior and turn on Don't Hide NavBar on Lock Screen...

Can't fix that.

**Comment by willx777** [comment]
Thanks for your reply. 

I'm sure this is caused by the app. I've just tested 3 times now. As soon as I disable Gesture Pill, the Flashlight Toggle in Quick Settings is back to normal immediately. 

Re. the icon cut out on lock screen, that option partially fixed it. When I'm on lock screen, I saw the icons still getting cut but quickly moved up a second later.

So you said there is no fix for the Camera app?

Last question, if I want to completely remove this app and go back to Samsung default navigation bar, how can I do this PROPERLY?

I disable "Hide navigation bar", then "Gesture Pill", and uninstall the app. I also applied this adb command "adb shell settings put global policy_control null*". The navigation bar is back, but it somehow is not completely back to normal as it should be. On some apps like Messages, Contacts and many more apps, the navigation bar turns completely black.

I also tried your suggested command  in Play Store review to other users "adb shell settings delete policy_control" (I don't remember exactly), I'm sure I copied correctly but it didn't work, it said something policy_control is not a valid argument or sort of.

Thanks

**Comment by zacharee** [comment]
I can reproduce the issue on my Note8 on Pie, so that's something.

The problem is that I can't figure out why it's happening. The only interaction with the flashlight is never even initialized until it's used.

**Comment by edwyard** [comment]
I have the same bug on a Pixel 3 XL running on pie, when nav bar is hidden and the pill activated it keeps turning off my flashlight. When only one or none is activated works just fine.

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases/tag/1.7.15

**Comment by willx777** [comment]
Thanks Zacharee. The latest 1.7.15 fixed the Flashlight toggle judge. 

Regarding the native navigation bar, after disable "Hide navigation bar", as mentioned above, in some apps like Settings, Messages and many more, the native navigation bar turns black with blurry icons. See screenshot below
https://imgur.com/a/Lx2MZdQ
