### ISSUE TITLE
Navigation Bar does not work when viewing pictures in full screen on FB Messenger Chat head

### ISSUE THREAD

**Issue by willx777** [zacharee/nobar-issues#41]
Navigation Bar does not work when viewing pictures in full screen on FB Messenger "Chat head".

However, viewing pictures in full screen when openning app (not in Chat head mode) still works well.

**Comment by zacharee** [comment]
Chat Heads also uses the overlay API. Since it was added last, it's on top. There's an option to work around this in Compatibility.

Sent from Nine
________________________________

**Comment by willx777** [comment]
Thanks. So which option should I choose in Compatibility?

The first 3 options are greyed out. I tried all other options, none worked.

**Comment by zacharee** [comment]
It's the first option in Experimental, sorry.

**Comment by willx777** [comment]
Thanks for your reply. 
I selected FB Messenger but it didn't work. I disabled "Gesture Pill" then re-enabled 3 times, still didn't work.

**Comment by willx777** [comment]
Please note that this is in Viewing picture in full screen while using Chat head.

The Navigation bar is working on Chat head itself for Chatting/typing activities (even without enable Experimental) but not for viewing pictures.

**Comment by zacharee** [comment]
Sorry, but that part can't be fixed.
