### ISSUE TITLE
Native Navigation bar appearance on Note9 Pie

### ISSUE THREAD

**Issue by willx777** [zacharee/nobar-issues#42]
Disabled Hide Navigation bar, also disabled Gesture Pill. The native navigation bar does not look normal.

In some apps like Settings, Messages, Clock, Calendar, eBay and many more, the native navigation bar turns black with very blurry icons (Recent, Home, Back). See screenshot below
https://imgur.com/a/Lx2MZdQ
https://imgur.com/a/YaC0OxX

I think it was always grey?

**Comment by willx777** [comment]
The Navigation Gesture app is very potential, but still quite laggy and buggy at times. Hence, I would like to go back to default Samsung navigation bar for now, and will try this app again in the next few months. 

Would appreciate if you can show me how to set the Navigation bar back to Samsung's default appearance.

Thanks!

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases/tag/1.9.1
