### ISSUE TITLE
Long swipe actions make the pill stuck away from original position when screen resolution changes

### ISSUE THREAD

**Issue by shmykelsa** [zacharee/nobar-issues#46]
**Describe the bug**
I've got two actions assigned to both swipe left and hold and swipe right and hold. One forces the orientation to landscape/portrait, and one triggers the one hand mode. If my finger is hold too much, then the pill will be in an odd position of the screen

**To Reproduce**
1. Swipe the pill and hold
2. Wait the action to be done
3. At this point your finger should be still pressing on the screen to reproduce the bug
4. The screen resolution will be changed and the pill is likely in the middle of the screen or with an offset from where it is expected it to be

**Expected behavior**
The pill should go back in place

**Screenshots/Recordings**
[Video here](https://youtu.be/7_SjyGYmb_k)

**Smartphone (please complete the following information):**
 - Device: LG V10
 - Android Version: 7.0
 - Navigation Gestures version: 1.7.19 (though it is not the first build I'm able to reproduce this issue)

**Comment by Kachelistic** [comment]
Mine got stuck too when I use Long swipe for screen off.
