### ISSUE TITLE
Pill draws over navigation bar

### ISSUE THREAD

**Issue by RikKoedoot** [zacharee/nobar-issues#48]
**What is the current behavior that should be changed?**
you cannot move the pill lower than the navigation bar (if not hidden)
**How should this behavior be changed?**
The pill should be movable so its on top of the navigation bar
**Additional context**
with apps like custom navigation bar from paphonb, you can hide your homebutton so it doesn't take the place where the pill will be placed, this option would be nice for people trying to emulate the android pie gestures, where the navigation bar stays at the bottom. 
![image](https://user-images.githubusercontent.com/29402532/52166577-62609400-270f-11e9-9cbc-334efcd3f2fd.png)

**Comment by zacharee** [comment]
We already tried this. Apps cannot draw over the navigation bar, only under. You won't be able to touch it.
