### ISSUE TITLE
Previous app gesture not working as intended

### ISSUE THREAD

**Issue by AGPlugged** [zacharee/nobar-issues#49]
**Describe the bug**
When using any gesture to go to previous app, the gesture only opens the recent apps menu instead.  Used on split-pill mode only. 

**To Reproduce**
1. Go to "Gestures"
2. Click on "section/swipe/tap"
3. Select "previous app nougat+"
4. Use gesture

**Expected behavior**
Should switch to the last app used. 

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - Android Version: 9
 - Navigation Gestures version: 1.7.20

**Additional context**
worked on previous versions of the app.

**Comment by Veed004** [comment]
Facing same issue in v1.10.1. 
Device: Asus Zenfone Max pro m2
Android version: 9
