### ISSUE TITLE
Backup and restore functionality

### ISSUE THREAD

**Issue by TruthIsIAmIronMan** [zacharee/nobar-issues#53]
Hoping this very useful feature will be implemented in a future version. The following are the scenarios where it's most useful:
1. **When toggling "Split pill" setting**  - settings go back to default regardless if this setting is turned on/off
1. **When performing factory reset** 
1. **When reinstalling the app**

App version: 1.7.7-19_01_12_1439_10<br>
Device: Galaxy Note 8<br>
Android: 9.0

**Comment by zacharee** [comment]
Beta 1.9.0 has this feature.
