### ISSUE TITLE
[Bug] Tasker event gestures

### ISSUE THREAD

**Issue by TruthIsIAmIronMan** [zacharee/nobar-issues#54]
On the gestures option, when I try to select "Tasker event" as an action, nothing happens instead of user-expected selection of which Tasker event should be fired when the gesture is triggered.

This is not the case when I choose other type of actions. Tasker event option is currently unusable.

App version: 1.7.7-19_01_12_1439_10
Device: Galaxy Note 8
Android: 9.0

**Comment by zacharee** [comment]
It's not meant to pop anything up. You have to create an Event profile in Tasker, choose Plugin, select Navigation Gestures, and then select the gesture you assigned to the Tasker Event action in Navigation Gestures.

**Comment by TruthIsIAmIronMan** [comment]
I see. Thank you for the clarification.


Regards,
Eric
