### ISSUE TITLE
NG app becomes irresponsive and crashes after sometime. 

### ISSUE THREAD

**Issue by midhunko** [zacharee/nobar-issues#56]
After the latest update on beta build, the app just won't react to my inputs often and it crashes after some time. Toggles for the hide navigation bar and enable gestures won't work and the whole UI lags before the app getting crashed. 

**To Reproduce**
Happened a couple of times when I was watching videos on YouTube and MX player. 

 - Device: Moto g4 play
 - Android Version: 8.1,Pixel Experience ROM, rooted. 
 - Navigation Gestures version:1.9.1
Crash ID : 1537412130111

**Comment by zacharee** [comment]
Is it any better on 1.9.5?

**Comment by midhunko** [comment]
Yeah, it's better now, I think.
