### ISSUE TITLE
Pill automatically hides even when hide after certain delay is disabled

### ISSUE THREAD

**Issue by mathuadi3** [zacharee/nobar-issues#57]
I have reset the setting of the app. But now the pill automatically hides after 5 seconds and it's really annoying to swipe up and then perform any gesture. I have checked every setting but there seems to be no way to stop this. Also the animation gesture is a little laggy. And sometimes instead of going back on left swipe, the pill goes straight to my home screen. Please fix!

**Comment by gtorelly** [comment]
I'm having the same issue after the last update. Pill hides automatically all the time, it's super annoying. I've tried tweaking every setting that hides the pill, but wasn't able to solve the problem. Moto Z Play on Android 8.0.0.

**Comment by zacharee** [comment]
What is the “last update”?

Sent from Mail for Windows 10

**Comment by gtorelly** [comment]
I'm using version 1.7.20 released on 2019-30-01. The annoying behavior
started happening last week. It's weird, because I was pretty sure that the
app auto-updated last week, but Google play says the last update was on Jan
30

**Comment by zacharee** [comment]
Can you update to the beta version?

**Comment by gtorelly** [comment]
So, this is weird, today the problem stopped happening. I didn't reboot, I
didn't install or uninstall any app. I don't know how to reproduce the
issue. I'd rather not install the beta for now, but if the problem persists
I will give it a try. Thank you for your help.
