### ISSUE TITLE
Bug: Notification symbols in status bar not dismissing

### ISSUE THREAD

**Issue by e-t-l** [zacharee/nobar-issues#58]
Here's something I've noticed only happens when this app is running, although I'm not sure why...

Normally, for apps that pop a notification on screen (e.g. messaging apps), if you swipe the pop-up to the side to dismiss it, the notification symbol remains in your status bar, and later you can swipe down on it to open the notificationsshade to view or dismiss the notification. Alternatively, if you tap the pop-up when it first appears, it typically takes you to the app in question, and automatically dismisses the symbol in the status bar.

However, if Navigation Gestures is running, when a notification pops on screen and I tap it to take me to the app, the symbol remains in the status bar. If I swipe open the notification shade, though, there is no notification, and only then does the symbol in status bar disappear.

Not sure exactly WHY this app would have this effect, but it's definitely the cause of the bug. I've tried playing around with the compatibility, experimental, and behavior settings to no avail. Any help would be greatly appreciated.

**Comment by e-t-l** [comment]
(forgot to mention, I'm running stock Android software on a Pixel 3. Everything is up to date.)

**Comment by zacharee** [comment]
This is reproducible on the OnePlus 6T, Galaxy Note8 and Galaxy Note9.

I don't think there's a fix.
