### ISSUE TITLE
Pill becomes unresponsive, lags and crashes.

### ISSUE THREAD

**Issue by mathuadi3** [zacharee/nobar-issues#66]
I have been facing this issue for a week now. The pill becomes unresponsive after a while and crashes. It lags and doesn't respond. I have tried clearing the data, cache and all the settings of the pill but nothing seems to work. I have been facing the issue after the new update. The overall experience is ruined by this and i am so disappointed.

**Comment by mathuadi3** [comment]
Why is my issue closed?

**Comment by mathuadi3** [comment]
What the hell? Why is my issue closed?

**Comment by zacharee** [comment]
Because you provided no details and didn't follow any template.

**Comment by mathuadi3** [comment]
I am new to this. But my issue is genuine.

**Comment by zacharee** [comment]
Please edit your original post with details such as app version, device, Android version, etc.
