### ISSUE TITLE
Feature request: Rotation toggle

### ISSUE THREAD

**Issue by e-t-l** [zacharee/nobar-issues#67]
Would it be possible to have a little rotation toggle pop up beside the pill when the phone senses rotation? (I've seen other apps accomplish similar things by having auto-rotation on at all times, but the having the actual screen orientation controlled by the app, so the screen is only allowed to fall into the correct orientation when the toggle is tapped.

**Comment by zacharee** [comment]
There's already a gesture for this. 

Adding a separate element wouldn't be compatible with a 100% pill width or invisible pill.

Sent from Nine
________________________________
