### ISSUE TITLE
Premium Status: Not Found!

### ISSUE THREAD

**Issue by yabeenico** [zacharee/nobar-issues#68]
Installed Premium Add-On but the app shows "Premium Status: Not Found!".
Reboot phone and reinstall the app not solved the problem.

Navigation Gestures version: 1.7.20
Add-On version: 2.1
Play Store version: 14.2.58-all [0] [PR] 239277684
Google Play services version: 15.0.90 (040400-231259764)

Android Model: Nexus 6P
Android version: 8.1.0
Android Baseband version: angler-03.88
Android Kernel version: 3.10.73-g309d642
Android Build number: OPM7.181205.001

Battery Optimization: disabled (both app and add-on)

**Comment by zacharee** [comment]
Tap the status text to see the reason it isn't.

**Comment by yabeenico** [comment]
Status text is 'User has been offline for more than 5 days'.
I have never used VPN or shut down the phone for such a long time.

**Comment by zacharee** [comment]
Do you have any proxy, ad-blocker or network-wide filter?

**Comment by yabeenico** [comment]
No, I've never used such applications like a VPN application on the Android or a filter on the route.

**Comment by zacharee** [comment]
Are you on a school, work or other organization network? What country are you in?

**Comment by yabeenico** [comment]
I'm in Japan, an University student.
But I have the Internet environment at my home.
What's the domain must I reach?
I'll check the reaching.

**Comment by yabeenico** [comment]
Today suddenly the problem have solved.
Only the versions of Play Store and Google Play Services are different from above.

Play Store version: 14.4.20-all [0] [PR] 242372321
Google Play Services version: 16.0.89 (040400-239467275)
