### ISSUE TITLE
pill freezes and becomes irresponsive

### ISSUE THREAD

**Issue by avikhagol** [zacharee/nobar-issues#69]
**Describe the bug**
Samsung J Max Tab : The pil bar freezes and wont respond to any gesture. enable/disable pill from app also wont fix it.

**To Reproduce**
1. Use your tablet for long
2. keep apps open in background and press home and then lock.
3. unlock the tablet. 
4. after unlocking it may or may not work fine and automatically starts working again too.

**Expected behavior**
pill freezes wont respond to gesture and will fix automatically during use.

**Screenshots/Recordings**
frozen:
https://drive.google.com/file/d/12Pu2WkrqkkzV_ZcwX0-2KBSyzqUROFI3/view?usp=drivesdk

https://drive.google.com/file/d/1gRR5QySBKvLWxMbw9AzSCjLroyarSPy-/view?usp=drivesdk
https://drive.google.com/file/d/1tyxAzNma1241Of1tt4EKlazL_NCTGSWS/view?usp=drivesdk
fixed: 
https://drive.google.com/file/d/1lhFPh-uL5Vm70KBCHlo2yhTIJWppPgaQ/view?usp=drivesdk

**Smartphone (please complete the following information):**
 - Device: Samsung J max 
- Android : 5.1.1 
 - Navigation Gestures version: 1.7.20
**Additional context**

**Comment by zacharee** [comment]
Navigation Gestures doesn't support tablets. This tablet is also very low-powered; it can't handle a heavy app like this.

**Comment by avikhagol** [comment]
it used to work flawlessly in older versions, anyways i will uninstall.
thanks for suggestion.
