### ISSUE TITLE
App specific location adjustment and behaviour?

### ISSUE THREAD

**Issue by Intergalactic1** [zacharee/nobar-issues#70]
Hi, 

Great app, quite intuitive. I'm guessing it isn't a small deal to implement but have you considered app specific location adjustment and behaviour?

**Comment by zacharee** [comment]
Sorry, that's not going to be implemented.

**Comment by Intergalactic1** [comment]
Through further use I notice it is more comprehensive than I thought but
what if you embedded a shortcut option for other apps to enable/disable
total visibility? Like bxactions could de/activate or a swipe etc.
Brilliant app btw it's my full time navigation
