### ISSUE TITLE
Impossible to restore a backup

### ISSUE THREAD

**Issue by shmykelsa** [zacharee/nobar-issues#71]
On Android 7.0, selecting the option to restore a backup, after having it done, will result in unselectable files.

![image](https://user-images.githubusercontent.com/9965637/55639679-3c687600-57ca-11e9-9ddc-7b50e57b8043.png)

In this example the backup file is on the bottom right corner.

No matter if the file is in SD Card or Internal Storage.

**Comment by zacharee** [comment]
Does the file have a size greater than 0B?

**Comment by shmykelsa** [comment]
Yes, 2.46 KB

**Comment by zacharee** [comment]
I can't reproduce this.

**Comment by shmykelsa** [comment]
![image](https://user-images.githubusercontent.com/9965637/55803572-e736a800-5ada-11e9-88a4-999c3c7a778f.png)
I can reproduce this also on Android 6.0

**Comment by zacharee** [comment]
I'm still unable to reproduce on an emulator running Android 7.0.

**Comment by BinkaDroid** [comment]
Restoring Backups from the same device (no factory reset or uninstalling app) work for me.
But restoring backups send over to another device isn't working, those backups are unselectable...

**Comment by zacharee** [comment]
Is this only happening on LG?

**Comment by BinkaDroid** [comment]
Here it was happening with Moto Z (Oreo) & Moto G4 plus (nougat)... both without SD-Card, just internal storage...

**Comment by zacharee** [comment]
I can't reproduce this on the Galaxy Note9 on 9.0, OnePlus 6T on 9.0, an emulator on 7.0 or an emulator on 6.0.

**Comment by BinkaDroid** [comment]
As I said, it only happens with backups from another device.

Following screenshot: left is unselectable (backup from another device), right would work (backup from same device).
![IMG_20190421_230704_867](https://user-images.githubusercontent.com/39274494/56475586-8b7cff00-648a-11e9-8214-945800f34aa6.jpg)

**Comment by zacharee** [comment]
I know. I tested it through the Google Drive mirror. Does that work? How are you copying the files over?

**Comment by shmykelsa** [comment]
So I have done some further investigation with 4 devices being: LG V10 running Android 7.0, Wiko Fever running Android 6.0, Huawei P8 Lite 2017 running Android 8.0 and Xiaomi Redmi Note 6 Pro running Android 8.1.0:

LG V10: won't let select any backup, whether it is made within the device or externally
Wiko Fever: same as LG V10
Xiaomi: will select backup made from the same device, but not others
Huawei: same as Xiaomi

So the files were sent over Telegram. Funny thing is, when I send a file via Telegram, I can save that into downloads, so I tried to save that same file sent via Telegram to downloads, and even that won't be accepted (even if it is basically the exact same file that I've sent, so made by the device itself).

Closer inspection: I passed the files to my PC and made a MD5 check (the one generated by the app and the one saved into downloads), just to see if Telegram manipulated them in any way, and they all returned the same hash.

**Comment by zacharee** [comment]
The files are saved with a custom MIME-type, which it looks like Telegram is stripping. I tested with a Telegram transfer on my Note9 and the downloaded file has an "unknown" type.

I'm not sure how this can be fixed. Do Nova Launcher backups behave the same way?

**Comment by shmykelsa** [comment]
> Do Nova Launcher backups behave the same way?

Nope
