### ISSUE TITLE
Pill transparency not working

### ISSUE THREAD

**Issue by MarkBurchard** [zacharee/nobar-issues#73]
**Describe the bug**
Pill is opaque at any transparency setting

**To Reproduce**
1. Go to Settings > Appearance > Colors
2. Click on either Pill Color or Pill Border Color
3. Move transparency slider to value > 0
4. Pill/border remains opaque.  Also colors do not change from grey/black.

**Expected behavior**
Transparency of Pill/Border

**Screenshots/Recordings**
Will add screenshot.

**Smartphone (please complete the following information):**
 - Device: Moto x4 Android One
 - Android Version: Pie-current
 - Navigation Gestures version: [e.g. 1.4.0-18_12_02_1010_57]

**Additional context**
On my 8.1 Moto e5 plus, this works.  On my Pie Moto x4 Android One, it doesn't.

**Comment by MarkBurchard** [comment]
App version 1.7.20

**Comment by zacharee** [comment]
Can you try on the latest beta?

**Comment by MarkBurchard** [comment]
Thanks, transparency is working for both pill and pill outline in Beta 1.9.5 from Play Store.  Don't see any regressions.  I'd buy it if I didn't already own it ;)
