### ISSUE TITLE
"Hide navigation bar" did not work on Google Pixel Android 9

### ISSUE THREAD

**Issue by dungtam73** [zacharee/nobar-issues#74]
My phone is running Android 9. After I do the factory reset then reinstall this app, I switch on the option "Hide navigation bar" but it not work

**Comment by zacharee** [comment]
Without version or device information, I can't do anything.

**Comment by dungtam73** [comment]
Google pixel 1, Android 9, latest version of this app from Google Play store
Please see these pictures:
https://photos.app.goo.gl/f9KEstQLs2hETYei7

**Comment by zacharee** [comment]
"latest version" is not useful information.

**Comment by dungtam73** [comment]
Version 1.7.20
Do you need anything else?

**Comment by zacharee** [comment]
Can you try the beta version?

**Comment by dungtam73** [comment]
Thanks for your support. Beta version is working well
