### ISSUE TITLE
S9+: NavBar flicker for a second, same for lockscreen shortcuts

### ISSUE THREAD

**Issue by evnvc** [zacharee/nobar-issues#77]
**Describe the bug**
The Navigation bar flickers sometimes on unlock: Randomly, when unlocking my screen, the stock navigation bar shows up for a second and then hides itself. Also the lockscreen shortcuts cut off just for a brief moment, see video below.

**To Reproduce**
1. Unlock via fingerprint
2. Navigation bar shows up and hides after a second
3. Unlock via hard press home
4. Lockscreen icons cut off

**Expected behavior**
Navigation Bar should be hidden at all times

**Screenshots/Recordings**
https://photos.app.goo.gl/XwscmGKy9hrfnTqZ6

**Smartphone (please complete the following information):**
 - Device: [S9+, SM- G965F]
 - Android Version: [9 - Pie, OneUI 1.0]
 - Navigation Gestures version: [1.10.1]

**Additional context**
Happens randomly

**Comment by zacharee** [comment]
This is unavoidable.
