### ISSUE TITLE
Lockscreen Issue on Version 1.10.3

### ISSUE THREAD

**Issue by Spegeli** [zacharee/nobar-issues#79]
**Describe the bug**
On Version 1.10.3 it seems that the Cut Off on the Lockscreen is not working anymore.
With Version 1.10.2 everythink works fine.

**Screenshots/Recordings**
Screenshot: http://i.epvpimg.com/rfSpgab.jpg

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 20 Pro
 - Android Version: 9
 - Navigation Gestures version: 1.10.3, 1.10.2

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases/tag/1.10.4

**Comment by Spegeli** [comment]
Its working, thx :-)

**Comment by zacharee** [comment]
I tested it on the OnePlus 6T and it works fine. Did you make sure the Don't Hide NavBar on Lock Screen option is on?
