### ISSUE TITLE
No hay sobreposición en pantalla de Xiaomi

### ISSUE THREAD

**Issue by Eduardnew** [zacharee/nobar-issues#81]
**Describe the bug**
Aún y con la configuración de no ocultar en pantalla de bloqueo. Marcadas todas la aplicaciones en behavior- blacklisting
Igual que en behavioe en Experimental settings-keep pill shown están marcadas todas la aplicaciones.

**Expected behavior**
Con esa configuración debería mostrarse en el loockscreen pero no es así.

**Smartphone (please complete the following information):**
 - Device: Xiaomi note 4
 - Android Version: 7.0
-  Miui Versión: 10.2 Global
 - Navigation Gestures version: 1.7.20

**Additional context**
Espero que me den una solución. La estoy probando para comprarla pero antes quiero estar seguro de que funciona.

**Comment by zacharee** [comment]
No es posible ponerla sobre la pantalla de bloqueo.
