### ISSUE TITLE
Question about NavBar in landscape 

### ISSUE THREAD

**Issue by Spegeli** [zacharee/nobar-issues#83]
On my Mate 20 Pro the original NavBar is shown in landscape. I found the "hide Navigation Bar in landscape" but the Option is disabled. Is this function not integrated yet?

Thx for your good work on this amazing app :-)

**Comment by zacharee** [comment]
The options were greyed out in Pie because of an automatic detection system. Seems like Huawei broke that, so 1.10.8 will let you enable the options.
