### ISSUE TITLE
Bug: Show Navbar lags

### ISSUE THREAD

**Issue by e-t-l** [zacharee/nobar-issues#84]
**Describe the bug**
The Show Navbar feature often lags, not appearing for a second or more (for example, when Show Navbar with Keyboard is toggled on, the keyboard will appear, then the Navbar will appear under it, shifting the entire keyboard up; if you already started typing, it messes you up). 

For Show Navbar in Selected Apps, it will sometimes stutter on screen, as if it can't decide whether to show or hide the Navbar. I've noticed this is particularly bade in Waze. 

Not sure why this is happening since I'm using a new phone with up-to-date software (no root), my storage is not particularly full, and I'm not running any resource-intensive programs. 

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - Android version: 9
 - Android build number: PQ2A.190405.003
 - Navigation Gestures version 1.7.20

**Comment by zacharee** [comment]
This is mostly unavoidable behavior. The app is set to only respond to UI changes every second. It could be faster, but at the potential cost of battery life and overall performance, especially on lower-end devices.
