### ISSUE TITLE
Pill is hidden after full screen 

### ISSUE THREAD

**Issue by ghost** [zacharee/nobar-issues#85]
**Describe the bug**
When viewing a picture in full screen the pill is hidden and then after the pill is not restored fully.

**To Reproduce**
1. Go to 'Google Play Store'
2. Click on an 'Image' to view screenshots of any app.
3. Go to 'Navigation Gestures'
4. The pill is *not* visible normally.

**Expected behavior**
The pill should be visible normally.

**Screenshots/Recordings**
![Screenshot_20190419-070002_Navigation_Gestures](https://user-images.githubusercontent.com/49779000/56413929-9e8da480-62bb-11e9-8e1a-026766751855.png)

**Smartphone (please complete the following information):**
 - Device: Oppo R7Plus
 - Android Version: 9 (LineageOS 16 nightly build)
 - Navigation Gestures version: 1.7.20

**Additional context**
 - Navigation Gestures settings: Default
 - Permissions (as far as *App info*): None
 - To recover: Restart the phone or clear storage and cache of Navigation Gestures
 - Other observations: When manually the pill is pulled down when watching YouTube and then after manually pulled up this issue is not arising.
 - Other observations: Vaguely remember the same happening on Android 8.1 (LineageOS 15).

**Comment by zacharee** [comment]
1.10.8
