### ISSUE TITLE
Accessibility service access keeps turning off by itself

### ISSUE THREAD

**Issue by MarkBurchard** [zacharee/nobar-issues#86]
**Describe the bug**
Accessibility service access somehow gets turned off and must be manually re-enabled

**To Reproduce**
Be me.  Experience several hangs/crashes when launching nobar from icon to get to Settings.  Sometimes this takes multiple attempts but it usually eventually works. But on a couple of occasions after trying to launch the app a dozen or so times, get frustrated and go to phone settings and force stop app and clear cache and check permissions.  Open up accessibility settings and find that they are off for nobar.  They had definitely been enabled and had not been turned off manually. Multiple other apps with accessibility access still have access enabled.  This has happened at least three or four times this week. I can't reliably reproduce it so don't have any logs. Crashlytics ID is enabled however.

**Expected behavior**
Normally accessibility services access for an app it does not need to be re-enabled frequently?  

**Screenshots/Recordings**
N/A

**Smartphone (please complete the following information):**
 - Device: Moto x4, Android One edition
 - Android Version: Pie with at least  March 1st updates
 - Navigation Gestures version: 1.10.7

**Additional context**
N/A

**Comment by zacharee** [comment]
Force stopping an app will deactivate its accessibility service.
