### ISSUE TITLE
Flipping phone to landscape automatically closes out of current app 

### ISSUE THREAD

**Issue by Aaron325** [zacharee/nobar-issues#87]
With autorotate on, flipping the phone sideways appears to make the nav bar press the home button twice. Even hitting fullscreen on YouTube replicates the problem. This doesn't happen when nav bar is turned off. 

1. Rotate phone 
2. App gets closed 
3. Occurs consistently every time since 2 updates ago 

 - Device: Pixel 2XL 
 - Android Version: QPP2.190228.023
 - Navigation Gestures version: 1.10.7

**Comment by liuhuoz** [comment]
Same issue to me
My info
Device: Xperia xz premium
Android Version: Pie in Feb match, stock rom 47.2.A.6.30
Navigation Gestures version: 1.10.7

**Comment by Aaron325** [comment]
I've noticed this doesn't occur when the nav bar is hidden though. I can rotate without problems, it's just annoying to have to hide it every time I want to watch a video.

**Comment by zacharee** [comment]
What gesture is assigned to Home?

____

Nevermind. I managed to reproduce and fix it.

**Comment by zacharee** [comment]
1.10.8

**Comment by liuhuoz** [comment]
The problem still happens in my device in Ver1.10.8
If you need a logcat, I could help.

**Comment by Aaron325** [comment]
Problem still occurring on my end too with 1.10.8. I can work around it by hiding the nav bar. Home is sent to the "tap" gesture.
