### ISSUE TITLE
Pill is invisible in App permissions on Android 9

### ISSUE THREAD

**Issue by ghost** [zacharee/nobar-issues#89]
**Describe the bug**
When viewing *App permissions* in Settings on Android 9 the pill goes invisible.

**To Reproduce**
1. Go to 'Settings' > 'Apps & notifications' >  'Navigation Gestures'.
Observe the pill is normal.
2. Touch/click 'Permissions'.
4. The pill is *not* visible at all.

**Expected behavior**
The pill should be visible normally.

**Screenshots/Recordings**
![Screenshot_20190423-064911_Settings](https://user-images.githubusercontent.com/49779000/56539190-b608ae00-6597-11e9-9c53-f31332f93bce.png)
![Screenshot_20190423-064923_Package_installer](https://user-images.githubusercontent.com/49779000/56539191-b608ae00-6597-11e9-94bd-b194814b22eb.png)

**Smartphone (please complete the following information):**
 - Device: Oppo R7Plus
 - Android Version: 9 (LineageOS 16 nightly build)
 - Navigation Gestures version: 1.7.20

**Additional context**
 - Navigation Gestures settings: Default

**Comment by zacharee** [comment]
This is a security feature in Android. Overlays are not allowed to display on app permissions pages or the APK installation confirmation screen.

**Comment by ghost** [comment]
@zacharee why not list such known behaviors of Android in **PROBLEMS?** page/screen inside the app.
