### ISSUE TITLE
new update means notifications pull down doesn't work

### ISSUE THREAD

**Issue by jobot4** [zacharee/nobar-issues#93]
**Describe the bug**

**To Reproduce**

**Expected behavior**
I set swipe right to pull down notifications, it worked before the update... im not rooted.

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Samsung note 4
 - Android Version: 6.0.1
 - Navigation Gestures version: 1.7.20

**Additional context**

**Comment by zacharee** [comment]
Does this still happen on 1.11.7?

**Comment by jobot4** [comment]
ill check it now
thanks

**Comment by jobot4** [comment]
yes on 1.11.7
i just downloaded an update but no change :( yet
should i try the beta?

**Comment by zacharee** [comment]
I can't reproduce this issue. The gesture works fine for me. Are you sure it's still properly assigned?

**Comment by zacharee** [comment]
Is this still happening on 1.11.12 or 1.12.1?

**Comment by jobot4** [comment]
hi
can u send me a link for any of these other versions please or
is there a jenkins etc slack channel or something i should subscribe to?

cheers
justin

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/releases

Sent from Nine
________________________________

**Comment by jobot4** [comment]
cool man
thats great ill get testing

**Comment by jobot4** [comment]
hi
i did the update from the play store but it has not fixed the issue
unfortunately

cheers
justin
