### ISSUE TITLE
Can't affect vibration length of 'Back' gesture

### ISSUE THREAD

**Issue by Abragus** [zacharee/nobar-issues#94]
**Describe the bug**
When using the back gesture, the vibration lasts for, with my settings, longer than all the other gestures. The vibration for that gesture seems to be unchangeable, and is always a set amount, independent of the vibration setting. All other gestures get the set vibration, and it doesn't matter what trigger is used, the 'Back' gesture is what causes the problem.

**To Reproduce**
1. Set any trigger to the 'Back' gesture. 
2. Use the trigger.
3. Compared to all other gestures, the vibration length should be different.

**Expected behavior**
All gestures should have the same vibration length. 

**Smartphone:**
 - Device: OnePlus 3T A3003
 - Android Version: 8.0.0
 - Navigation Gestures version: 1.7.20

**Comment by zacharee** [comment]
This is a problem with OxygenOS. It can't be fixed.

**Comment by Abragus** [comment]
Oh, I'm sorry. Thanks for the great app and quick support!
