### ISSUE TITLE
Keyboard Cursor Navigation Mode

### ISSUE THREAD

**Issue by sslater11** [zacharee/nobar-issues#96]
Just an Idea, but I used to have an HTC Legend which had a mini trackpad on it. I used to like using it and miss the ability to move the text cursor up, down, left and right.

How about when they keyboard is open, we have different gestures so that I can swipe in the direction to move the cursor. Swipe and hold will repeatedly press the arrow key. Double tap the pill to revert it to it's normal function, or double tap just coses the keyboard. 

I feel like the pill should be able to change colour if it's in a different mode too, just as a visual reminder.

P.S. Loving this app!

**Comment by zacharee** [comment]
https://github.com/zacharee/nobar-issues/issues/29
