### ISSUE TITLE
Split pill doesn't register interaction when keyboard is active

### ISSUE THREAD

**Issue by andrewchelladurai** [zacharee/nobar-issues#98]
**Description**
Split pill doesn't register interaction when keyboard is active

**Steps to reproduce**
Enabled the Split Pill
Enable option - Don't move Pill when keyboard is shown

Now focus on any text field
Ideally the pill must be at the bottom of the keyboard and not the top
Ideally you should be able to swipe from the left, centre and bottom of the pill to trigger the actions - example, back or show recents or "go home"
But when you try to swipe, the keyboard captures the swipes and not the pill.

**Expected behavior**
Pill must capture the swipes and trigger the actions.

**Screenshots/Recordings**
Let me know if you need a screen recording and I'll make one.

**Smartphone (please complete the following information):**
 - Device: [Pixel 2 - Stock Android with May Security Patch]
 - Android Version: [Pie]
 - Navigation Gestures version: [ Production 1.11.7]

**Additional context**

**Comment by zacharee** [comment]
Does the pill show over the keyboard?

**Comment by andrewchelladurai** [comment]
No, the pill stays below the keyboard but it doesn't register the swipes.

**Comment by andrewchelladurai** [comment]
Not sure if the crashes are related to the issue I reported
However I am going to keep adding them whenever they happen on this comment.

FYI - the app's crashed and restarted a few times since I've reported this.

Crash Analytics ID - 1557509360316

**Comment by zacharee** [comment]
Your ID doesn't return any matches. Do you have any adblockers or VPNs enabled?

**Comment by andrewchelladurai** [comment]
I've got a VPN enabled.

**Comment by zacharee** [comment]
Make sure Google Analytics and Firebase domains are whitelisted.

**Comment by andrewchelladurai** [comment]
Alright, I'll do that.
The  wait for the next crash to happen and share the ID with you then.

**Comment by zacharee** [comment]
The ID has to be enabled before any crashes happen. You kept it enabled, right?

**Comment by andrewchelladurai** [comment]
Yes

**Comment by andrewchelladurai** [comment]
I think I just had another crash

1557509360316

**Comment by zacharee** [comment]
That was an app-not-responding. What were you doing before it popped up?

**Comment by andrewchelladurai** [comment]
Blank Screen.
But the action I was performing before it happened was

1 - Whitelist the Google Analytics and Firebase Domains
2 - Toggled the Enable Gesture Quick Settings Tile
3 - Navigated to the application
4 - ANR occurred / Basically a blank screen

So I cleared the application from the recents menu
Relaunched the application and saw the restart button.

**Comment by zacharee** [comment]
Is this still an issue on 1.11.12 or 1.12.1?

**Comment by andrewchelladurai** [comment]
I just updated it
I'll check and let you know.

**Comment by andrewchelladurai** [comment]
Hey, the ANR hasn't occured on the new version since the upgrade.
