### ISSUE TITLE
On Screen Finger Print Reader Not Working

### ISSUE THREAD

**Issue by allenmarkham3** [zacharee/nobar-issues#99]
**Describe the bug**
Navigation Gestures seems to be blocking (laying on top of?) the on screen finger print reader and not allowing it to read finger prints.

**To Reproduce**
Using the on screen finger print reader on the lock screen to launch a home screen or any app secured and opened by a finger print.

**Expected behavior**
I would expect the on screen finger print reader to accurately read my finger prints as it does when Navigation Gestures in not turned on.

**Screenshots/Recordings**
.

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy @10+
 - Android Version: [e.g. Pie Android version 9.0
 - Navigation Gestures version: 1.11.7
**Additional context**
I'll provide anything I can to help.

**Comment by zacharee** [comment]
Hiding the navigation bar shifts the lock screen content down, including the fingerprint icon. Put your finger about 1cm higher than the icon.

**Comment by allenmarkham3** [comment]
Got it and it works.  Thanks for the quick response.  I consider this closed.
